#!/bin/bash
# AWS Deployment Script for Drew Command Center & Prime Parking  
# Fixed version - Generated by Drew AI Assistant

echo "🚀 Starting AWS deployment..."

# Configure AWS CLI with your credentials
aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
aws configure set default.region us-east-1

# Get current available Python platforms
echo "🔍 Finding current Python platform..."
PLATFORM=$(aws elasticbeanstalk list-available-solution-stacks --query 'SolutionStacks[?contains(@, `Python 3.9`) && contains(@, `Amazon Linux 2`)]' --output text | head -1)
echo "Using platform: $PLATFORM"

# Create Elastic Beanstalk application for Command Center
echo "📦 Creating Command Center application..."
aws elasticbeanstalk create-application \
    --application-name "drew-command-center" \
    --description "Drew AI Command Center - Premium Flask Application"

# Create Elastic Beanstalk environment  
echo "🌍 Creating Command Center environment..."
aws elasticbeanstalk create-environment \
    --application-name "drew-command-center" \
    --environment-name "drew-command-center-prod" \
    --solution-stack-name "$PLATFORM" \
    --option-settings \
        Namespace=aws:autoscaling:launchconfiguration,OptionName=InstanceType,Value=t3.small \
        Namespace=aws:elasticbeanstalk:environment,OptionName=EnvironmentType,Value=SingleInstance

echo "⏳ Waiting for environment to be ready (this takes ~5 minutes)..."
aws elasticbeanstalk wait environment-updated --environment-name "drew-command-center-prod"

echo "✅ AWS infrastructure deployed! Next: Upload application code"
echo "🔗 Environment URL will be available at: $(aws elasticbeanstalk describe-environments --environment-names drew-command-center-prod --query 'Environments[0].CNAME' --output text)"